# Generated by Django 4.1.2 on 2022-10-06 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=100)),
                ("slug", models.SlugField()),
                (
                    "image",
                    models.ImageField(
                        blank="True",
                        null=True,
                        upload_to="uploads/images/<django.db.models.fields.CharField>",
                    ),
                ),
                ("content", django_quill.fields.QuillField()),
                (
                    "status",
                    models.CharField(
                        choices=[("brouillon", "Brouillons"), ("publié", "Publié")],
                        default="brouillon",
                        max_length=200,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
