# Generated by Django 4.1.2 on 2022-10-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_category_comment_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(blank=True, null=True, to="articles.category"),
        ),
    ]
