# Generated by Django 4.1.2 on 2022-10-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(blank=True, to="articles.category"),
        ),
    ]
